---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r include=FALSE}
library(tidyverse)
library(plotly)
library(htmlwidgets)
library(flexdashboard)
```

Column {data-width=650}
------------------------------------------------------------------------------------

### Pizza Restaurants in Manhattan by Latitude and Longitude  

```{r}
nyc_inspect = read_csv(file = "./data/nyc_inspec.csv") %>% 
  select(camis, dba, boro, zipcode, cuisine_description, critical_flag, score, census_tract, grade, grade_date, latitude, longitude)
  
nyc_pizza =
  drop_na(nyc_inspect) %>% 
  filter(cuisine_description == "Pizza", 
         boro == "Manhattan",
         grade != "Z",
         grade != "P")

nyc_pizza %>%
  mutate(text_label = str_c("Grade: ", grade, "\nScore: ", score)) %>% 
  plot_ly(
    x = ~latitude, y = ~longitude, type = "scatter",
    color = ~grade, text = ~text_label, alpha = 0.5)

```

Column {data-width=350}
-----------------------------------------------------------------------

### Number of A-Grade Pizza Restaurants by Borough of NYC 

```{r}
nyc_all = 
  drop_na(nyc_inspect) %>% 
  filter(cuisine_description == "Pizza",
         grade == "A",)

count(nyc_all, boro) %>% 
  mutate(boro = fct_reorder(boro, n)) %>% 
  plot_ly(x = ~boro, y = ~n, color = ~boro, type = "bar", colors = "viridis") %>% 
  layout((title = "Number of A-Grade Pizza Restaurants by Borough of NYC"),
          xaxis = list(title = "Borough"),
          yaxis = list(title = "N of A-Grade Pizza Restaurants"))

```

### Average Health Code Score of 'Grab-and-Go' Restaurants in Manhattan, by Cuisine Type

```{r}
nyc_score =
  drop_na(nyc_inspect) %>% 
  filter(boro == "Manhattan",
         grade != "Z",
         grade != "P",
         critical_flag == "N",
         cuisine_description == c("Donuts","Bagels/Pretzels","Pizza","Sandwiches","Bakery", "Hotdogs","Juice, Smoothies, and Fruit Salads")) 

nyc_score %>% 
plot_ly(x = ~cuisine_description, y = ~score, type = "box") %>% 
  layout((title = "Average Health Code Score of 'Grab-and-Go' Restaurants in Manhattan, by Cuisine Type \n(Where Higher Scores Correspond to Higher Quantity/More Serious Violations"),
          xaxis = list(title = "Cuisine Type"),
          yaxis = list(title = "Inspection Score"))
```


